#!/bin/bash

# git fixup with fzf
#   fixupの対象をfzfで選択してコミットを作る
#   対象ファイルのステージは事前に実行しておくこと

DIR=$(cd $(dirname ${BASH_SOURCE}); pwd)
. $DIR/common.sh || exit 1

require_fzf

cid=$(command git log --oneline -100 | command grep -v fixup | command fzf | command awk '{ print $1 }')
[ -n "$cid" ] && command git commit --fixup=$cid
