#!/bin/bash

DIR=$(cd $(dirname ${BASH_SOURCE}); pwd)
. $DIR/common.sh || exit 1

command cat << EOF
git-sub is installed: $DIR.
Now added command is ...
$(command ls -p $DIR | command grep -v / | command grep -E '^git-' | command grep -v subping | command sed -E 's/-/ /' | command awk '{ print "  " $0 }')
EOF
