#!/bin/bash
set -euo pipefail

DIR=$(cd $(dirname ${BASH_SOURCE}); pwd)
. "$DIR/common.sh"

CNT="${1:-0}"

# オプションは ハイフン + 数字(0〜999)
if command expr "$CNT" : '^-[0-9]\{1,3\}$' > /dev/null ; then
    CNT="${CNT/-/}"
else
    err "invalid args: $*"
fi

target() {
    case "$1" in
        "0") echo HEAD ;;
        "1") echo HEAD~ ;;
        * ) echo "HEAD~$1"
    esac
}

TO=$(target $CNT)
FROM=$(target "$(($CNT+1))")

command git diff "$FROM..$TO"
